title: Dr. Suiyang Liao

show_downloads: true
theme: jekyll-theme-minimal


# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
