title: Suiyang Liao PHD

theme: jekyll-theme-minimal


title                    : "Your Name / Site Title"
title_separator          : "-"
name                     : &name "Your Name"


author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Your Sidebar Name"
  pronouns         : # example: "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Earth"
  employer         : "Red Brick University"
  uri              : # URL
  email            : "none@example.org" 
