title: Suiyang Liao, PhD

# header:
#   logo: "https://github.com/liaosuiyang/liaosuiyang.github.io/blob/main/CA6AA504-95FD-4683-8BB2-6BEE594D3C36_1_105_c.jpeg"

description: this is created by me on 20250330
show_downloads: false
theme: minima


# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
